spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/basket_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:app}
    password: ${SPRING_RABBITMQ_PASSWORD:app}
  application:
    name: pricing-service
  config:
    import: "optional:consul"
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      config:
        enabled: true
        prefix: config
        default-context: application
        profile-separator: '-'
        format: YAML
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 1m
        deregister: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env,refresh,busrefresh

server:
  port: ${PORT:9003}

basket:
  base-url: http://basket:9002

price:
  events:
    exchange: ${PRICE_EVENTS_EXCHANGE:price.events}
    routing-key: ${PRICE_UPSERT_ROUTING_KEY:price.upserted}